---
- name: Include elrepo.yml
  ansible.builtin.include_tasks: elrepo.yml
  when:
    - (ansible_facts["distribution"] == "Amazon" and
      ansible_facts["distribution_major_version"] == "2") or
      (ansible_facts["distribution"] in [ "RedHat", "CentOS", "Rocky", "AlmaLinux" ])
