---
- name: Include elrepo.yml
  ansible.builtin.include_tasks: elrepo.yml
  when:
    - (ansible_distribution == "Amazon" and
      ansible_distribution_major_version == "2") or
      (ansible_distribution in [ "RedHat", "CentOS", "Rocky", "AlmaLinux" ])
