---
molecule_exceptions:
  - variation: "Ubuntu*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "Debian*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "Fedora*"
    reason: "repo only supports RedHat/CentOS Server"
  - variation: "centos-stream9"
    reason: "repo not supported"
  - variation: "amazonlinux"
    reason: "repo not supported"

molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current"]
    platforms:
      - "centos7"
      - "centos-stream8"
      - "centos-stream9"
      - "ubi8"
      - "ubi9"
      - "rockylinux8"
      - "rockylinux9"
      - "almalinux8"
      - "almalinux9"
