---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_facts['distribution'] }}"
          - "ansible_distribution_major_version => {{ ansible_facts['distribution_major_version'] }}"
          - "ansible_os_family  => {{ ansible_facts['os_family'] }}"
          - "ansible_system  => {{ ansible_facts['system'] }}"

    - name: Test if repository exists and is enabled
      community.general.ini_file:
        path: "/etc/yum.repos.d/elrepo.repo"
        section: "elrepo"
        option: enabled
        value: "1"
        no_extra_spaces: true
        mode: "0644"
      check_mode: true
      register: molecule_repository
      failed_when: (molecule_repository is changed) or (molecule_repository is failed)
